go run _example/demo_all.go &
go run toolsgui/_example/label.go &
go run toolsgui/_example/button.go &
go run toolsgui/_example/entry.go &
go run toolsgui/_example/progressbar.go &
go run toolsgui/_example/coordinate.go &
go run toolsgui/_example/fractal.go &
go run toolsgui/_example/histogramm.go &
go run toolsgui/_example/image.go &